
### 유저 생성
POST http://localhost:3000/user/create
content-type: application/json

{
    "user_nickname" : "TnkYun",
    "user_password" : "test1234"
}

### 유저 정보 가져오기
GET  http://localhost:3000/user/getUser/8

### 유저 정보 업데이트
PUT  http://localhost:3000/user/update/8
content-type: application/json

{
    "user_nickname" : "TTnkYYUN",
    "user_password": "test4321"
}

###유저 삭제 
DELETE http://localhost:3000/user/delete/8

