###회원가입

POST http://localhost:3000/auth/register
content-type: application/json

{
    "user_id": "john1234",
    "user_nickname" : "john2",
    "user_password" : "changeme"
}

### 두번째아이디 회원가입

POST http://localhost:3000/auth/register
content-type: application/json

{
    "user_id": "2",
    "user_nickname" : "kdjytva22s38",
    "user_password" : "a1234567"
}

### 로그인
POST http://localhost:3000/auth/login
content-type: application/json

{
    "user_id": "john1234",
    "user_nickname" : "john2",
    "user_password" : "changeme"
}

### 두번째아이디 로그인
POST http://localhost:3000/auth/login
content-type: application/json

{
    "user_nickname" : "kdjy2238",
    "user_password" : "a1234567"
}


### GUARD 테스트
curl http://localhost:3000/auth/test-guard -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVVc2VyX0R0IjoxLCJ1c2VyX2NvZGUiOjEsInVzZXJfaWQiOiJqb2huMTIzNCIsInVzZXJfbmlja25hbWUiOiJqb2huMiIsImN1cnJlbnRSZWZyZXNoVG9rZW4iOiIkMmIkMTAkQUMyTTVNMmJWS2FRWFd4dDU0Tm1hdVlraWVtaWgzMmlpNDM5L2NlQUMweXRPRFpIdHd0TEMiLCJjdXJyZW50UmVmcmVzaFRva2VuRXhwIjpudWxsLCJpYXQiOjE2ODk4NzMzMjQsImV4cCI6MTY4OTg3MzM1NH0.Pmy_q5o_S7qtZmV77zB3uOWGEEloAIgIlchuQDjE0Go"
{    "user_id": "john1234","user_nickname" : "john2","user_password" : "changeme""iat":...,"exp":...}


### jwt 테스트
