###회원가입

POST http://localhost:3000/auth/register
content-type: application/json

{
    "user_nickname" : "kdy2238",
    "user_password" : "a1234567"
}

### 두번째아이디 회원가입

POST http://localhost:3000/auth/register
content-type: application/json

{
    "user_nickname" : "kdjy2238",
    "user_password" : "a1234567"
}

### 로그인
POST http://localhost:3000/auth/login
content-type: application/json

{
    "user_nickname" : "kdy2238",
    "user_password" : "a1234567"
}

### 두번째아이디 로그인
POST http://localhost:3000/auth/login
content-type: application/json

{
    "user_nickname" : "kdjy2238",
    "user_password" : "a1234567"
}
